DATA:
  IMG_SIZE: 900
MODEL:
  TYPE: swin_mlp
  NAME: swin_mlp_tiny_c6_patch4_window8_256
  DROP_PATH_RATE: 0.2
  NUM_CLASSES: 2
  SWIN_MLP:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 6, 2 ]
    NUM_HEADS: [ 16, 32, 64, 128 ]
    WINDOW_SIZE: 12